### ISSUE TITLE
:lady_beetle: [Broken Pipe at 55% on L9]

### ISSUE THREAD

**Issue by DarkCTO** [pete4abw/lrzip-next#130] opened 2023-07-08 11:52 UTC
### lrzip-next Version

lrzip-next version 0.11.3

### lrzip-next command line

lrzntar -vv -L 9 Anarchy\ Reigns\ \(USA\)\ \(En\,Ja\,Fr\,Es\,It\)/ > output.txt

### What happened?

Crashed at 55% on certain tar, happens on L9, default (L7) is OK.
Computer froze for a few seconds before process is killed!

```
lrzntar -vv -L 9 Anarchy\ Reigns\ \(USA\)\ \(En\,Ja\,Fr\,Es\,It\)/ > output.txt
/usr/local/bin/lrzntar: line 24: 2716575 Broken pipe             tar c "$s"
     2716576 Killed                  | lrzip-next "${p[@]}"
```

### What was expected behavior?

Umm... no crash please?

### Steps to reproduce

Only happens with certain files, did not happen with lrzip.

### Relevant log output

```shell
The following options are in effect for this COMPRESSION.
Threading is ENABLED. Number of CPUs detected: 16
Detected 33,502,130,176 bytes ram
Nice Value: 19
Show Progress
Max Verbose
Output Filename Specified: /run/media/kudy/DATA/temp/Anarchy Reigns (USA) (En,Ja,Fr,Es,It).tar.lrz
Temporary Directory set as: /tmp/
Compression mode is: LZMA. LZ4 Compressibility testing enabled
Compression level 9
RZIP Compression level 9
Initial LZMA Dictionary Size: 134,217,728
MD5 Hashing Used
Heuristically Computed Compression Window: 106 = 10,600MB
Storage time in seconds 1,392,583,840
Succeeded in testing 11,167,375,360 sized mmap for rzip pre-processing
Chunk size: 11,167,375,360
Byte width: 5
Dictionary Size reduced to 100,663,296
Threads reduced to 9
Per Thread Memory Overhead is 1,163,935,744
Succeeded in testing 16,059,110,058 sized malloc for back end compression
Using up to 9 threads to compress up to 620,412,928 bytes each.
Beginning rzip pre-processing phase
hashsize = 4,194,304.  bits = 22. 64MB
Starting sweep for mask 1
Starting sweep for mask 3
Starting sweep for mask 7
Starting sweep for mask 15
Starting sweep for mask 31
Chunk:  1%
Starting sweep for mask 63
Chunk:  2%
Chunk:  3%
Starting sweep for mask 127
Chunk:  4%
Chunk:  5%
Starting thread 0 to compress 620,412,928 bytes from stream 1
lz4 testing OK for chunk 620,412,928. Compressed size = 99.70% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 0...
Chunk:  6%
Starting sweep for mask 255
Chunk:  7%
Chunk:  8%
Chunk:  9%
Chunk: 10%
Chunk: 11%
Starting thread 1 to compress 620,412,928 bytes from stream 1
lz4 testing OK for chunk 620,412,928. Compressed size = 96.58% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 1...
Chunk: 12%
Chunk: 13%
Starting sweep for mask 511
Chunk: 14%
Chunk: 15%
Chunk: 16%
Starting thread 2 to compress 620,412,928 bytes from stream 1
lz4 testing OK for chunk 620,412,928. Compressed size = 90.46% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 2...
Chunk: 17%
Chunk: 18%
Chunk: 19%
Chunk: 20%
Chunk: 21%
Chunk: 22%
Starting thread 3 to compress 620,412,928 bytes from stream 1
lz4 testing OK for chunk 620,412,928. Compressed size = 98.51% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 3...
Chunk: 23%
Chunk: 24%
Chunk: 25%
Chunk: 26%
Starting sweep for mask 1,023
Chunk: 27%
Starting thread 4 to compress 620,412,928 bytes from stream 1
lz4 testing OK for chunk 620,412,928. Compressed size = 97.73% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 4...
Chunk: 28%
Chunk: 29%
Chunk: 30%
Chunk: 31%
Chunk: 32%
Chunk: 33%
Starting thread 5 to compress 620,412,928 bytes from stream 1
lz4 testing OK for chunk 620,412,928. Compressed size = 94.23% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 5...
Chunk: 34%
Chunk: 35%
Chunk: 36%
Chunk: 37%
Chunk: 38%
Chunk: 39%
Starting thread 6 to compress 620,412,928 bytes from stream 1
lz4 testing OK for chunk 620,412,928. Compressed size = 99.40% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 6...
Chunk: 40%
Chunk: 41%
Chunk: 42%
Chunk: 43%
Chunk: 44%
Starting thread 7 to compress 620,412,928 bytes from stream 1
lz4 testing OK for chunk 620,412,928. Compressed size = 98.47% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 7...
Chunk: 45%
Chunk: 46%
Chunk: 47%
Chunk: 48%
Chunk: 49%
Chunk: 50%
Starting thread 8 to compress 620,412,928 bytes from stream 1
lz4 testing OK for chunk 620,412,928. Compressed size = 99.30% of test size 10,485,760, 1 Passes
Starting lzma backend compression thread 8...
Chunk: 51%
Chunk: 52%
Starting sweep for mask 2,047
Chunk: 53%
Chunk: 54%
Chunk: 55%
```

### Please provide system details

```
                 `:osssssss+-              OS: EndeavourOS Linux x86_64 
               `:+sssssssssso/.            Host: 82K6 Legion 7 16ITHg6 
             `-/ossssssssssssso/.          Kernel: 6.3.9-arch1-1 
           `-/+sssssssssssssssso+:`        Uptime: 2 days, 5 hours, 19 mins 
         `-:/+sssssssssssssssssso+/.       Packages: 1191 (pacman) 
       `.://osssssssssssssssssssso++-      Shell: bash 5.1.16 
      .://+ssssssssssssssssssssssso++:     Resolution: 1920x1080, 1920x1080, 3840x2160 
    .:///ossssssssssssssssssssssssso++:    WM: i3 
  `:////ssssssssssssssssssssssssssso+++.   Theme: Adwaita [GTK2], Arc-Darker [GTK3] 
`-////+ssssssssssssssssssssssssssso++++-   Icons: Adwaita [GTK2], Qogir [GTK3] 
 `..-+oosssssssssssssssssssssssso+++++/`   Terminal: xfce4-terminal 
   ./++++++++++++++++++++++++++++++/:.     Terminal Font: Source Code Pro 10 
  `:::::::::::::::::::::::::------``       CPU: 11th Gen Intel i9-11980HK (16) @ 4.900GHz 
                                           GPU: NVIDIA GeForce RTX 3080 Mobile / Max-Q 8GB/16GB 
                                           Memory: 3611MiB / 31950MiB 
```

### Additional Context

In case you need to investigate the file itself, let me know.
I can also execute any command on my side.

**Comment by pete4abw** [comment] 2023-07-08 12:39
> lrzntar -vv -L 9 Anarchy\ Reigns\ (USA)\ (En,Ja,Fr,Es,It)/ **> output.txt**

Format of command is incorrect. The `tar` command is already piped to `lrzip-next`.
You may also wish to consider using `tar --use-compress-program lrzip-next` instead. `lrzntar` is a bloated and overly complicated script IMO.  See [this wiki page](https://github.com/pete4abw/lrzip-next/wiki/Using-tar-with-lrzip-next).

**Comment by DarkCTO** [comment] 2023-07-08 16:10
How do I use it without STDIN/STDOUT?

**Comment by pete4abw** [comment] 2023-07-08 18:27
lrzntar uses the tar command. The output filename is the directory you are tar'ing. So
`lrzntar [lrzip-next options] mydirectory`
will create an lrz file with the name **mydirectory.lrz**

Unless you have a small embedded system with limited ram, there is no need...NO NEED...to use `-U`. I'm wondering about your filename which needs a lot of escape characters. I think you will also need to escape the characters of the output file if `-o` is given. I cannot duplicate your crash. Try not using `-o`.

> $ ./lrzntar -h
lrzntar GNU/bash wrapper script for lrzip-next and tar input/output over directories.
Copyright (C) George Makrydakis 2009-2011,2013
Copyright (C) Con Kolivas       2011,2012
Updated 2022 Peter Hyman for lrzip-next compatibility
>
> Usage : lrzntar [lrzip-next options] <directory>
Result: a lrzip-next tarball is produced.
Extras: when an lrzip-next tarball is used with -d, -O, it gets extracted:
>
>  -h: will display this message.
 -d: <path1> will decompress a <path1> lrzip-next tarball to current directory.
 -O: <path2> will decompress a -d specified lrzip-next tarball to <path2> path.
 -f: will force overwrites.
>
> Notice:
>  - The input argument is always last, all options and their arguments precede.
> - The -O flag is an option flag, goes before: (-O <somedir> <input arg>).
> - You can use the remaining options of lrzip-next as they were.
> - lrznuntar is equivalent to lrzntar [options] -d <filename>.
> - This script exists because of how lrzip-next behaves.
> - Beware the -f flag, it stands for what it says...
>

**Comment by DarkCTO** [comment] 2023-07-08 18:34
> will create an lrz file with the name mydirectory.lrz

It always create .tar.lrz for me, not just .lrz

![2023-07-08-113258_1117x615_scrot](https://github.com/pete4abw/lrzip-next/assets/99158109/7987cdb0-4215-404c-adc2-384d52636cf9)

**Comment by DarkCTO** [comment] 2023-07-08 18:41
I don't know how to use the software without STDIN/STDOUT to maximize compression window.
The best I get is only 10G, and certain command only give 5G
`Heuristically Computed Compression Window: 106 = 10,600MB
`
I have 32GB RAM, should use way more than this.

**Comment by DarkCTO** [comment] 2023-07-08 18:46
> Try not using -o

https://github.com/pete4abw/lrzip-next/wiki/Piping-with-lrzip-next

According to this, using -o is critical. Also lrzipntar generates .tar.lrz file unless there's option to dictate otherwise.

**Comment by pete4abw** [comment] 2023-07-08 18:49
> I don't know how to use the software without STDIN/STDOUT to maximize compression window.
> The best I get is only 10G, and certain command only give 5G
> `Heuristically Computed Compression Window: 106 = 10,600MB
> `
> I have 32GB RAM, should use way more than this.

By default, compression window is 1/3 system ram. When STDIN/OUT are used, the default is 1/6. This is to allow for the piping program memory needs. You can always increase the compression window with the `-w` option.

Please close this issue of resolved. Thank you.

**Comment by pete4abw** [comment] 2023-07-08 19:20
> > Try not using -o
> 
> https://github.com/pete4abw/lrzip-next/wiki/Piping-with-lrzip-next
> 
> According to this, using -o is critical. Also lrzipntar generates .tar.lrz file unless there's option to dictate otherwise.

If you're using `lrzip-next`, then yes. But if you're using lrzntar, NO. It creates is own output file.

`STDIN | lrzip-next -o myfile.lrz` or
`STDIN | lrzip-next >myfile.lrz`

Should both work.

**Comment by DarkCTO** [comment] 2023-07-08 19:26
You did not tell me how to use this lrzip-next without STDIN/STDOUT nor an instruction on your wiki.
The main bug is a crash on 55% on L9, which is not being resolved.
lrzip-next does not support folder, so to make .lrz and not .tar.lrz we need the -o

`tar -cf- Anarchy\ Reigns\ \(USA\)\ \(En\,Ja\,Fr\,Es\,It\)/ | lrzip-next -L9 -vv -o "Anarchy Reigns (USA) (En,Ja,Fr,Es,It).lrz"
`

This crash is reproducible actually, but the files in question are huge to upload. 
So you want the file? About 12GBs.
Failure rate is 10/150 files so that's not acceptable but up to you if you want to fix it.
If you won't, please add won't fix label and close the issue on your own.

You can also tell me which bash commands to monitor RAM,CPU etc... to figure out the problem if you want to fix but cannot download the file for whatever reason.

**Comment by DarkCTO** [comment] 2023-07-08 19:36
> lrzntar uses the tar command. The output filename is the directory you are tar'ing. So
> lrzntar [lrzip-next options] mydirectory
> will create an lrz file with the name mydirectory.lrz

Also if you wrote lrzntar from lrztar and you said the extension is .lrz when in reality is .tar.lrz then this claim is false. Yes the output filename is the folder name, but the extension is .tar.lrz.

**Comment by pete4abw** [comment] 2023-07-08 19:42
> > lrzntar uses the tar command. The output filename is the directory you are tar'ing. So
> > lrzntar [lrzip-next options] mydirectory
> > will create an lrz file with the name mydirectory.lrz
> 
> Also if you wrote lrzntar from lrztar and you said the extension is .lrz when in reality is .tar.lrz then this claim is false. Yes the output filename is the folder name, but the extension is .tar.lrz.

A typo. .tar.lrz is correct.

**Comment by pete4abw** [comment] 2023-07-08 19:50
Closing as not a bug. You can't pipe when using lrzntar.

**Comment by DarkCTO** [comment] 2023-07-08 19:53
I am SO confused right now.

`lrzntar -vv -L 9 Anarchy\ Reigns\ (USA)\ (En,Ja,Fr,Es,It)/
`

What is the pipe here???????

**Comment by DarkCTO** [comment] 2023-07-08 19:53
Fine. If you are just closing stuff and not helping. I won't submit any other issues.

**Comment by pete4abw** [comment] 2023-07-08 21:39
> I am SO confused right now.
> 
> `lrzntar -vv -L 9 Anarchy\ Reigns\ (USA)\ (En,Ja,Fr,Es,It)/ `
> 
> What is the pipe here???????
> 
> This command caused crash on my OS.
> 
> I thought pipe is `lrzntar | something else` which I did not do.

If you examined the `lrzntar` script, you will see this line where all the action occurs:
```
        tar c "$s" | lrzip-next "${p[@]}"
        x=$?
    }
    return $x
```
**$s** is the directory being tar'red. **${p[\@]}** are the lrzip-next options passed to `lrzntar`. The output file will be the directory name followed by .tar.lrz as you noted.

You could also make this a two step process yourself. First tar the directory. Second perform lrzip-next on the tarfile. If you do this you can take advantage of the maximum compression window since it will occupy 2/3 of ram (I think I wrote one third before. That is incorrect. 

Your script could be:
```
tar -cf file.tar yourdirectory
lrzip-next [options] file.tar
```

From `rzip.c`
```
1008         /* Optimal use of ram involves using no more than 2/3 of it, so we
1009          * allocate 1/3 of it to the main buffer and use a sliding mmap
1010          * buffer to work on 2/3 ram size, leaving enough ram for the
1011          * compression backends */
1012         control->max_mmap = control->maxram;
1013         round_to_page(&control->max_mmap);
1014 
1015         /* Set maximum chunk size to 2/3 of ram if not unlimited or specified
1016          * by a control window. When it's smaller than the file size, round it
1017          * to page size for efficiency. */
1018         if (UNLIMITED)
1019                 control->max_chunk = control->st_size;
1020         else if (control->window)
1021                 control->max_chunk = control->window * CHUNK_MULTIPLE;
1022         else
1023                 control->max_chunk = control->ramsize / 3 * 2;
```

**Comment by DarkCTO** [comment] 2023-07-08 21:54
OK I will try two step command. Yes I expect 2/3 of my 32 GB RAM at least, ~20GB window.

You were saying I pipe lrzntar myself which I did not. the pipe was done internally.
So, if there is a broken pipe, I'm not sure I caused it. I simply provide folder name, internal of lrzntar does the piping.
So the crash is there because of this piping that I did not write, I'm trying to find out why.

When I encounter the crash and can make it reproducible, I will reply to this thread with steps.

**Comment by pete4abw** [comment] 2023-07-08 21:59
> OK I will try two step command. Yes I expect 2/3 of my 32 GB RAM at least, ~20GB window.
> 
> You were saying I pipe lrzntar myself which I did not. the pipe was done internally. So, if there is a broken pipe, I'm not sure I caused it. I simply provide folder name, internal of lrzntar does the piping. So the crash is there because of this piping that I did not write, I'm trying to find out why.
> 
> When I encounter the crash and can make it reproducible, I will reply to this thread with steps.

You piped the output of lrzntar by using the **\>outputfile** in your command. `lrzntar` required only one option: the directory to be lrz'ed. Your original commandline is incorrect:
`lrzntar -vv -L 9 Anarchy\ Reigns\ (USA)\ (En,Ja,Fr,Es,It)/ > output.txt`

I'm also unclear how the **()** characters would be interpreted when piped. They may also have to be escaped.

**Comment by DarkCTO** [comment] 2023-07-08 22:03
No, >outputfile or not, it's still crashing.
I put the escapes but I actually used it in my script where I put that name inside double quotes (Bash).

`lrzntar -vv -L9 "$folder"`

And it crashes. Sorry if I didn't make it clear enough.

Maybe it's the file as I lrzntar from a .tar.lrz I compressed with lrzip -L9 (smaller blocks) and then compress with lrnzip -L9.

But then I download a new file but still crashes.

**Comment by pete4abw** [comment] 2023-07-08 22:20
> No, >outputfile or not, it's still crashing.
> I put the escapes but I actually used it in my script where I put that name inside double quotes (Bash).
> 
> `lrzntar -vv -L9 "$folder"`
> 
> And it crashes. Sorry if I didn't make it clear enough.
> 
> Maybe it's the file as I lrzuntar from a .tar.lrz I compressed with lrzip -L9 (smaller blocks) and then compress with lrnzip -L9.
> 
> But then I download a new file but still crashes.

You'll have to provide more info on the directory and its contents. For example the total size of the directory the type of files, the amount of free disk space on the drive. Is the directory write protected, etc. Over the years no one has reported a problem. Reopening...

PS. I will be off line until Monday.

**Comment by pete4abw** [comment] 2023-07-09 21:42
Use single quotes or escape all () characters, although I think your problem is different. I cannot duplicate it. Check free disk space in the directory you are running `lrzntar` from as well as swap space and your **TMP** directory as well as write permissions. I tested this with a very large file at `-L9` and it ran smoothly. Run these commands from the video directory:
`du -d1 -hc .`
and then
`df -h`

Then we'll have a better idea of why  you have a crash.

**Comment by DarkCTO** [comment] 2023-07-10 02:25
I deleted the problematic files now I cannot reproduce either. When it happens again I can revisit this.
600GiB free space where I run lrzntar
I have no swap space.
We can close this until I can encounter this again.

**Closed** 2023-07-10 10:11 UTC
Labels: invalid
